### ISSUE TITLE
How to get the her_hvg_cut_1000.npy file?

### ISSUE THREAD

**Issue by lmxmercy** [yrjia1015/THItoGene#2]
"her_hvg_cut_1000.npy"
"skin_hvg_cut_1000.npy"
Where should I to download these two files, thx!

**Comment by yrjia1015** [comment]
Hello, thank you for following THItoGene. The files you need are located in the link below. 
[https://github.com/yrjia1015/THItoGene/tree/main/data](url)

Best regards,
Yuran
