### ISSUE TITLE
Trained model reproduction

### ISSUE THREAD

**Issue by 2001229323jyf** [yrjia1015/THItoGene#3]
Hello, this is a good job and I am very interested in your work. But after I downloaded your model parameters, I failed to reproduce the results of the experiment, showing that the version number of the pytorch_lightning was missing from the model. Do you have any good solutions, and it would be appreciated if you could provide a complete and working parametric model. Looking forward to your reply, thank you.

**Comment by yrjia1015** [comment]
Hi, thank you for your interest in THItoGene! We have provided the models used for benchmarking in the paper at [https://www.synapse.org/#!Synapse:syn52503858/files/](url). You can directly run these models. We have listed the required packages for our training environment in the requirements.txt file, with pytorch_lightning version 2.0.6. We have retested the availability of the models and the environment. In our testing environment, everything runs smoothly.

If you encounter any problems, you can use our latest Conda environment for testing:[https://github.com/yrjia1015/THItoGene/blob/main/THItoGene.yml](url)

Best regards,
Yuran
